package cache

import (
	"fmt"
	"strings"
)

// Registry-config formats `print-registries` can emit.
const (
	FormatK3s  = "k3s"  // k3s /etc/rancher/k3s/registries.yaml (the default)
	FormatCRIO = "crio" // containers-registries.conf(5), read by CRI-O and podman
	FormatOKD  = "okd"  // OpenShift/OKD cluster manifests: IDMS + ITMS + image.config
)

// Formats lists the accepted --format values, default first.
var Formats = []string{FormatK3s, FormatCRIO, FormatOKD}

// Render emits the mirror configuration for every configured cache in the
// requested format. host is how the consumer reaches the caches; the port of
// each is PortBase + its index in Upstreams, exactly as `up` publishes them.
func (e *Engine) Render(format, host string, fallback bool) (string, error) {
	switch format {
	case "", FormatK3s:
		return e.RenderRegistries(host, fallback), nil
	case FormatCRIO:
		if !fallback {
			// registries.conf has no "mirror only" switch: `blocked = true`
			// blocks the mirrors as well. Refuse rather than silently fall back.
			return "", fmt.Errorf("--no-fallback is not expressible in registries.conf (CRI-O always falls back to the upstream)")
		}
		return e.RenderCRIO(host), nil
	case FormatOKD:
		return e.RenderOKD(host, fallback), nil
	}
	return "", fmt.Errorf("unknown --format %q (want one of: %s)", format, strings.Join(Formats, ", "))
}

// RenderRegistries produces a k3s /etc/rancher/k3s/registries.yaml that
// points each upstream at its host-published cache, with the real upstream
// listed second as a fallback so a stopped cache degrades to direct pulls
// instead of breaking deploys.
//
// host is the address k3s nodes use to reach the host (DefaultHost by
// default; the ctl-tool wiring resolves it via --add-host host-gateway).
// When fallback is false only the cache endpoint is emitted.
func (e *Engine) RenderRegistries(host string, fallback bool) string {
	if host == "" {
		host = DefaultHost
	}
	var b strings.Builder
	b.WriteString("# generated by regcachectl — k3s pull-through cache mirrors\n")
	b.WriteString("mirrors:\n")
	for i, u := range Upstreams {
		b.WriteString(fmt.Sprintf("  %q:\n", u.Host))
		b.WriteString("    endpoint:\n")
		b.WriteString(fmt.Sprintf("      - %q\n", fmt.Sprintf("http://%s:%d", host, e.Port(i))))
		if fallback {
			b.WriteString(fmt.Sprintf("      - %q\n", u.Remote))
		}
	}
	return b.String()
}

// mirrorHost is the cache for upstream index i as a registry host:port — the
// form registries.conf and the OpenShift mirror sets want (no scheme).
func (e *Engine) mirrorHost(host string, i int) string {
	return fmt.Sprintf("%s:%d", host, e.Port(i))
}

// RenderCRIO produces a containers-registries.conf(5) with one [[registry]]
// per upstream and its cache as an insecure (plain-HTTP) [[registry.mirror]].
// A pull-through cache keeps the upstream's repository paths, so the mirror
// location is the bare cache host. CRI-O tries the mirror first and the
// upstream itself last, so a stopped cache degrades to direct pulls.
func (e *Engine) RenderCRIO(host string) string {
	if host == "" {
		host = DefaultHost
	}
	var b strings.Builder
	b.WriteString("# generated by regcachectl — containers-registries.conf(5) pull-through cache mirrors\n")
	for i, u := range Upstreams {
		fmt.Fprintf(&b, "\n[[registry]]\n  location = %q\n\n", u.Host)
		fmt.Fprintf(&b, "  [[registry.mirror]]\n    location = %q\n    insecure = true\n", e.mirrorHost(host, i))
	}
	return b.String()
}

// RenderOKD produces OpenShift/OKD cluster manifests: an ImageDigestMirrorSet
// and an ImageTagMirrorSet that send every upstream to its cache, and the
// image.config.openshift.io `cluster` Image marking the caches insecure (they
// speak plain HTTP). Without fallback the mirror sets use NeverContactSource,
// so a node never pulls from the upstream directly.
//
// Applying the `cluster` Image replaces its spec: merge the insecureRegistries
// into an existing one rather than applying this over it on a running cluster.
func (e *Engine) RenderOKD(host string, fallback bool) string {
	if host == "" {
		host = DefaultHost
	}
	policy := ""
	if !fallback {
		policy = "    mirrorSourcePolicy: NeverContactSource\n"
	}
	mirrors := func(field string) string {
		var b strings.Builder
		fmt.Fprintf(&b, "  %s:\n", field)
		for i, u := range Upstreams {
			fmt.Fprintf(&b, "  - source: %s\n    mirrors:\n    - %s\n%s", u.Host, e.mirrorHost(host, i), policy)
		}
		return b.String()
	}
	var b strings.Builder
	b.WriteString("# generated by regcachectl — OKD/OpenShift pull-through cache mirrors\n")
	b.WriteString("apiVersion: config.openshift.io/v1\nkind: ImageDigestMirrorSet\nmetadata:\n  name: regcache\nspec:\n")
	b.WriteString(mirrors("imageDigestMirrors"))
	b.WriteString("---\napiVersion: config.openshift.io/v1\nkind: ImageTagMirrorSet\nmetadata:\n  name: regcache\nspec:\n")
	b.WriteString(mirrors("imageTagMirrors"))
	b.WriteString("---\napiVersion: config.openshift.io/v1\nkind: Image\nmetadata:\n  name: cluster\nspec:\n  registrySources:\n    insecureRegistries:\n")
	for i := range Upstreams {
		fmt.Fprintf(&b, "    - %q\n", e.mirrorHost(host, i))
	}
	return b.String()
}
