package cache

import (
	"fmt"
	"strings"
)

// RenderRegistries produces a k3s /etc/rancher/k3s/registries.yaml that
// points each upstream at its host-published cache, with the real upstream
// listed second as a fallback so a stopped cache degrades to direct pulls
// instead of breaking deploys.
//
// host is the address k3s nodes use to reach the host (DefaultHost by
// default; the ctl-tool wiring resolves it via --add-host host-gateway).
// When fallback is false only the cache endpoint is emitted.
func (e *Engine) RenderRegistries(host string, fallback bool) string {
	if host == "" {
		host = DefaultHost
	}
	var b strings.Builder
	b.WriteString("# generated by regcachectl — k3s pull-through cache mirrors\n")
	b.WriteString("mirrors:\n")
	for i, u := range Upstreams {
		b.WriteString(fmt.Sprintf("  %q:\n", u.Host))
		b.WriteString("    endpoint:\n")
		b.WriteString(fmt.Sprintf("      - %q\n", fmt.Sprintf("http://%s:%d", host, e.Port(i))))
		if fallback {
			b.WriteString(fmt.Sprintf("      - %q\n", u.Remote))
		}
	}
	return b.String()
}
